const $=id=>document.getElementById(id); let map,layer,routes=[];
const positions={nus:{lon:103.776,lat:1.296},north:{lon:103.786,lat:1.438},bay:{lon:103.855,lat:1.287}};
function preferences(){return {target_distance_km:Number($('distance').value),duration_min:Number($('duration').value),horizon_min:Number($('horizon').value),location:positions[$('location').value]||null,max_access_distance_km:$('access').value?Number($('access').value):null};}
async function api(path,body){const res=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await res.json();if(!res.ok)throw Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail));return data;}
function draw(selected){if(!window.L){$('map').hidden=true;$('fallback').hidden=false;$('fallback').replaceChildren();const p=document.createElement('p');p.textContent='Map library unavailable. Route shapes shown below (separate local coordinate panels).';$('fallback').append(p);for(const r of selected){const pts=r.geometry.coordinates,xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]);const minx=Math.min(...xs),miny=Math.min(...ys),dx=Math.max(...xs)-minx||1,dy=Math.max(...ys)-miny||1;const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 600 280');const line=document.createElementNS(svg.namespaceURI,'polyline');line.setAttribute('points',pts.map(p=>`${20+560*(p[0]-minx)/dx},${260-220*(p[1]-miny)/dy}`).join(' '));line.setAttribute('fill','none');line.setAttribute('stroke','#24684c');line.setAttribute('stroke-width','3');const title=document.createElement('p');title.textContent=r.name;$('fallback').append(title,svg);svg.append(line);}return;}
if(!map){map=L.map('map').setView([1.36,103.82],11);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:19}).addTo(map);}if(layer)map.removeLayer(layer);layer=L.featureGroup(selected.map((r,i)=>L.polyline(r.geometry.coordinates.map(p=>[p[1],p[0]]),{color:i?'#bb792c':'#24684c',weight:5}))).addTo(map);if(selected.length)map.fitBounds(layer.getBounds(),{padding:[25,25]});}
function render(run){routes=run.routes;draw(routes);$('warnings').textContent=run.warnings.join(' ');$('cards').replaceChildren();const rows=run.recommendations.length?run.recommendations:[];if(!rows.length){$('cards').textContent='No routes satisfy your access limit.';return;}for(const [i,rec] of rows.entries()){const r=routes.find(r=>r.route_id===rec.route_id),c=run.conditions.find(c=>c.route_id===r.route_id),p=run.predictions.find(p=>p.route_id===r.route_id);const card=document.createElement('article');card.className='card';const title=document.createElement('h3');title.textContent=`${i+1}. ${r.name}`;card.append(title);for(const text of [`${r.distance_km.toFixed(3)} km · ${r.kind}`,`Rain observation: ${c.rainfall_mm===null?'Unavailable':c.rainfall_mm+' mm'} · ${c.quality}`,`Observed: ${c.observed_at||'N/A'} · ${c.source}`,`Forecast (${p.horizon_min} min): ${p.rain_probability===null?'Unknown':(100*p.rain_probability).toFixed(0)+'%'} · ${p.is_mock?'SIMULATED':p.source}`,`Score ${rec.score} · ${r.status}`,...rec.reasons]){const el=document.createElement('p');el.textContent=text;card.append(el);}const env=(run.environment||[]).find(e=>e.route_id===r.route_id);if(env){const wrap=document.createElement('div');wrap.className='environment-scroll';const table=document.createElement('table');table.className='environment';const head=document.createElement('tr');for(const label of ['Metric / window','Value','State / delivery','Source / distance','Observation / fetched']){const th=document.createElement('th');th.textContent=label;head.append(th);}table.append(head);for(const m of env.metrics){const tr=document.createElement('tr');tr.dataset.metric=m.metric;tr.dataset.state=m.state;for(const value of [m.metric+' / '+m.aggregation_window,m.category_value??(m.value===null?'Unavailable':Number(m.value.toFixed(2))+' '+m.unit),m.state+' / '+m.delivery,m.source+' / '+(m.location_name||'N/A')+(m.station_distance_km===null?'':' / '+m.station_distance_km+' km'),(m.observed_at||'N/A')+' / '+(m.fetched_at||'N/A')]){const td=document.createElement('td');td.textContent=value;tr.append(td);}tr.title=m.reason+' · '+m.match_method+' · source updated '+(m.source_updated_at||'not supplied');table.append(tr);}wrap.append(table);card.append(wrap);} const button=document.createElement('button');button.textContent='Show route';button.onclick=()=>draw([r]);card.append(button);$('cards').append(card);}}
async function busy(fn){document.querySelectorAll('button').forEach(b=>b.disabled=true);$('status').textContent='Working…';try{await fn();$('status').textContent='Updated.';}catch(e){$('status').textContent=e.message;}finally{document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
$('preferences').onsubmit=e=>{e.preventDefault();busy(async()=>render(await api('/api/recommendations',preferences())));};
$('refresh').onclick=()=>busy(async()=>{const report=await api('/api/refresh',{});$('ingestion').textContent=report.status+' · '+report.sources.map(s=>s.source+': '+s.status+(s.error?' ('+s.error+')':'')).join(' | ');render(await api('/api/recommendations',preferences()));});
$('chat').onsubmit=e=>{e.preventDefault();busy(async()=>{const r=await api('/api/chat',{message:$('message').value,preferences:preferences()});$('answer').textContent=r.message;$('trace').textContent=JSON.stringify(r.trace,null,2);if(r.run)render(r.run);});};
busy(async()=>{const h=await api('/api/health');$('mode').textContent=`Data: ${h.data_mode} / Agent: ${h.agent_mode}`;render(await api('/api/recommendations',preferences()));});
