"""Team interfaces: consumers receive typed structures, not filesystem paths."""
from datetime import datetime
from typing import Protocol
from .models import Route,Conditions,Prediction,Preferences,Recommendation,Run
from .environment import CollectionBatch,IngestionRun,RouteEnvironment,EnvironmentRisk
class EnvironmentCollector(Protocol):
    source: str
    def collect(self) -> tuple[CollectionBatch,int]: ...
class EnvironmentRepository(Protocol):
    def load_routes(self) -> list[Route]: ...
    def ingestion_worker_lock(self): ...
    def save_worker_status(self,status:dict) -> None: ...
    def database_status(self,source_kind:str="live") -> dict: ...
    def source_due(self,source:str,source_kind:str,interval_seconds:int,as_of:datetime) -> bool: ...
    def ingest(self,batch:CollectionBatch,run:IngestionRun) -> IngestionRun: ...
    def record_failure(self,run:IngestionRun) -> None: ...
    def environment_snapshot(self,source_kind:str,as_of:datetime) -> tuple: ...
    def save_route_environment(self,environments:list[RouteEnvironment],mappings:list) -> None: ...
    def save_run(self,run:Run) -> None: ...
class RouteEnvironmentReader(Protocol):
    def get_route_environment(self,route_id:str,as_of:datetime|None=None) -> RouteEnvironment: ...
class Predictor(Protocol):
    def predict(self,conditions:list[Conditions],horizon_min:int) -> list[Prediction]: ...
class EnvironmentRiskAssessor(Protocol):
    def assess(self,environments:list[RouteEnvironment]) -> list[EnvironmentRisk]: ...
class Recommender(Protocol):
    def rank(self,routes:list[Route],conditions:list[Conditions],predictions:list[Prediction],preferences:Preferences) -> list[Recommendation]: ...

class CollectionFailure(Exception):
    def __init__(self,message,attempts): super().__init__(message);self.attempts=attempts
